### ISSUE TITLE
Application Node Information Message Request Failure

### ISSUE THREAD

**Issue by ah-brown** [IgnitionModuleDevelopmentCommunity/ZWaveDriver#1]
Hi Travis, 
I am getting the following message in the Ignition logs with its failure to find search for nodes.

	Message node-FF-msg-03 failed: {"node": FF, "message": org.imdc.zwavedriver.zwave.messages.ApplicationNodeInformationMessage$Request@49e19f24}

Currently using the following:
Ignition Version : V8.0.6, or V8.0.16
 Z-Stick : Aeotec Z-Stick Gen5+

Is there anything i can look at to fix this?
[Ignition-ESM-ignition_Ignition-backup-20201023-1134.gwbk.zip](https://github.com/IgnitionModuleDevelopmentCommunity/ZWaveDriver/files/5426737/Ignition-ESM-ignition_Ignition-backup-20201023-1134.gwbk.zip)

**Comment by iatraviscox** [comment]
Try restarting the module and let me know if you get that error again.

**Comment by ah-brown** [comment]
Yes, I had tried restarting the module, Ignition Service and have tried on another computer running Windows 10 Pro (Rather than Windows Server 19).

**Comment by iatraviscox** [comment]
It appears you are getting messages back from the Z-Wave stick. The ApplicationNodeInformation message didn't receive a response and it is up to the Z-Wave stick to send a response or not. Can you verify that you have tags in the designer under the Z-Wave tag provider? It did find your home.

**Comment by iatraviscox** [comment]
Do you have nodes added to the controller? You can certainly try updating the firmware.

**Comment by ah-brown** [comment]
Yes i did connect the a devices to the controller. I will factory reset and then will try again.

**Comment by iatraviscox** [comment]
I don't know if there is an issue or not. Some requests don't get responses back.
