### ISSUE TITLE
'getting started' section of the Readme needs device install/config info

### ISSUE THREAD

**Issue by allandaly** [IgnitionModuleDevelopmentCommunity/ZWaveDriver#3]
You guys are awesome. I love the Ignition product and your Maker edition is excellent to use for projects and learning at home.

I am trying to get the Z Wave module up and running and I'm in good shape so far following the guidance in the readme. My setup is:

* Linux Ubuntu 20.04
* Igntion v8.1 Maker
* Aeotec Z Stick Gen5
* Aoetec Multisensor 6

I'm just trying to get Ignition to talk to the multisensor. Seems like a simple first step to take.

The Readme explains how to get the Z Wave module installed and configured and I'm all set on that front. But there is no guidance on how to configure the device side. Following the usual Ignition logic I figured I would 'add a device' and find a Z Wave type of device profile there then I'd follow the step. But there's no Z Wave device type and I'm not sure what to do next.

Can you please put some basic guidance into the Readme about how to handle the device side of the setup?

Thanks a ton. Great product. Really appreciate what you guys do.

-Allan

**Comment by iatraviscox** [comment]
I have added more information about adding and removing devices. Let me know if there are additional questions.
