### ISSUE TITLE
ZWaveDriver module errors

### ISSUE THREAD

**Issue by allandaly** [IgnitionModuleDevelopmentCommunity/ZWaveDriver#4]
I'm working on getting the ZWaveDriver module installed and running on my system. (By the way, thank you for adding in the additional 'device side' info into the Readme.) I was able to initially load the module and see a green 'Running' status on the Modules Status page, but now I'm seeing 'Faulted' instead.

![image](https://user-images.githubusercontent.com/1977598/106362600-96f48f80-62d8-11eb-96fa-55b0c57d015d.png)

My environment is:
* Linux/Ubuntu 20.04
* Ignition v8.1.1 Maker
* Aeotec Z Stick Gen5

When the module was working previously, I was able to see the 'ZWave' Settings option in the 'Config' menus and I set the port as '/dev/ttyACM0' in that location.

The logs show this error message coming from the ZWaveDriver module.
* Error starting module org.imdc.zwavedriver
* java.lang.NoSuchMethodError: 'void com.fazecast.jSerialComm.SerialPort.setBaudRate(int)'

Here's a screenshot of the logs with a few notes and highlights.

![image](https://user-images.githubusercontent.com/1977598/106362772-7aa52280-62d9-11eb-900d-763ff10fd729.png)

Things I've tried:
1. Uninstalled and reinstalled the module
2. Stopped and restarted the Ignition server
3. Rebooted the linux system

None of these changed the situation.

I do see the jSerialComm v2.5.2 jar file in the Ignition jar-cache.

![image](https://user-images.githubusercontent.com/1977598/106362879-1afb4700-62da-11eb-8a20-7bf179eb3d87.png)

I looked inside the jar file and do see what looks like the right class in there.

![image](https://user-images.githubusercontent.com/1977598/106362925-5c8bf200-62da-11eb-91e5-e92ac056f2a8.png)

Questions:
1. Do you have any advice as to how to address this issue?
2. I would like to try removing or changing the port setting but since the module is not starting I cannot access the Config section to do that. Can you tell me another way to find/edit the port config value inside of Ignition somewhere?

Thanks for your help.

-Allan

**Comment by iatraviscox** [comment]
I just published a fix for that issue. The problem is that Ignition 8.1 contains the same library I use and it was a newer version. I have updated that and it should work just fine. Try downloading the new modl file and let me know.

**Comment by allandaly** [comment]
Hi Travis,

Thanks for updating this. I installed your new version and everything is working.

I have more questions now about how to actually interact with the Z Wave devices through Ignition but I'm going to do my homework first before posting anything further.

Thanks again.

-Allan
